### ISSUE TITLE
zsh: command not found: gpt-translate

### ISSUE THREAD

**Issue by xiajunwen1007** [aemartinez/gpt-latex-translator#4]
Thanks a lot for your tool. I encountered a problem when installation. After installing the tool via the comman `pip install gpt-translate`, I cannot use it within the terminal. The error is `zsh: command not found: gpt-translate`. By the way, I am a Mac user. What should I do to run it correctly. Thanks a lot.

**Comment by aemartinez** [comment]
Hi @xiajunwen1007 , thanks for your interest! 

After cloning the repository you need to run the command `pip install .` in the root directory of the repository. Could you please paste here the complete output this command gives you? Also, could you paste here the output of the command `echo $PATH`? I suspect the installation directory is not registered in your PATH...

**Comment by xiajunwen1007** [comment]
Thanks a lot for your reply. I've figured out the solution. Before that, I didn't clone the repository and installed gpt-translate by `pip install gpt-translate` directly. It would be more friendly to new users like me with a more comprehensive installation steps. The following steps could be added. At last, thanks a lot for your hard work.
```
git clone https://github.com/aemartinez/gpt-latex-translator
cd gpt-latex-translator
pip install .
```
